# Generated by Django 2.0.2 on 2018-02-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'canceled'), (0, 'idea'), (1, 'pending'), (2, 'in progress'), (3, 'done')], default=0),
        ),
    ]
